server:
  port: 8092

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/keledb?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: xukele
    password: kele123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations:
    - classpath:mappers/*-mapper.xml
  configuration:
    use-generated-keys: true
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
